# 🎯 NumPy Practice Exercises

**Course:** Machine Learning Foundations  
**Topic:** NumPy Array Manipulation  

---


## 📦 Import NumPy
Run this cell first to import NumPy for all exercises.


In [ ]:
# Import numpy




---
## Exercise 1: Create a 1D Array

### Problem:
Create a NumPy array containing the numbers from **1 to 20** (inclusive).

**Expected Output:**
```
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
```


In [ ]:
# Exercise 1: Your Code Here
arr = # Your code here

print(arr)


## Exercise 2: Create a Matrix of Zeros 

### Problem:
Create a **5×5** matrix (2D array) filled with zeros.

**Expected Output:**
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```


In [ ]:
# Exercise 2: Your Code Here
matrix = # Your code here

print(matrix)


## Exercise 3: Extract Specific Elements

### Problem:
Given the array below, extract:
1. The element at position `[2, 3]`
2. The entire 3rd row
3. The entire 2nd column

```python
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])
```

**Expected Outputs:**
```
1. 120
2. [ 90 100 110 120]
3. [ 20  60 100]
```


In [ ]:
# Exercise 3: Your Code Here


# 1. Element at [2, 3]
element = # Your code here
print('1. Element:', element)

# 2. Entire 3rd row
third_row = # Your code here
print('2. Third row:', third_row)

# 3. Entire 2nd column
second_col = # Your code here
print('3. Second column:', second_col)


## Exercise 4: Boolean Filtering 

### Problem:
Given the array of test scores below, find all scores that are **greater than or equal to 80**.

```python
scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])
```

**Expected Output:**
```
[82 90 85 92 88 95]
```


In [ ]:
# Exercise 4: Your Code Here
scores = np.array([75, 82, 90, 68, 85, 92, 78, 88, 95, 72])

passing_scores = # Your code here

print('Passing scores (≥80):', passing_scores)


## Exercise 5: Calculate Statistics 

### Problem:
Given the array of daily temperatures, calculate:
1. The **mean** (average) temperature
2. The **maximum** temperature
3. The **minimum** temperature
4. The **standard deviation**

```python
temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])
```

**Expected Output (approximately):**
```
Mean: 76.6°F
Max: 82°F
Min: 72°F
Std Dev: 3.07°F
```


In [ ]:
# Exercise 5: Your Code Here
temperatures = np.array([72, 75, 78, 82, 79, 73, 76, 80, 77, 74])

mean_temp = # Your code here
max_temp = # Your code here
min_temp = # Your code here
std_temp = # Your code here

print(f'Mean: {mean_temp}°F')
print(f'Max: {max_temp}°F')
print(f'Min: {min_temp}°F')
print(f'Std Dev: {std_temp:.2f}°F')


## Exercise 6: Reshape an Array 

### Problem:
Create an array of numbers from **1 to 12**, then reshape it into a **3×4** matrix.

**Expected Output:**
```
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [ ]:
# Exercise 6: Your Code Here
arr = # Create array 1-12
matrix = # Reshape to 3×4

print(matrix)


## Exercise 7: Element-wise Operations 

### Problem:
Given two arrays, perform these operations:
1. Add them together
2. Multiply them element-wise
3. Find which elements of `a` are greater than elements of `b`

```python
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])
```

**Expected Outputs:**
```
1. [15 45 45 75 95]
2. [ 50 500 450 1400 2250]
3. [True False True True True]
```

In [ ]:
# Exercise 7: Your Code Here
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 25, 15, 35, 45])

# 1. Addition
sum_ab = # Your code here
print('1. Sum:', sum_ab)

# 2. Multiplication
product_ab = # Your code here
print('2. Product:', product_ab)

# 3. Comparison
comparison = # Your code here
print('3. a > b:', comparison)


## Exercise 8: Create a Random Array 

### Problem:
Create a **4×5** matrix of random integers between **1 and 100** (inclusive).

**Expected Output (your numbers will be different):**
```
[[23 45 67 12 89]
 [34 56 78 90 11]
 [45 67 89 23 45]
 [56 78 90 34 56]]
```



In [ ]:
# Exercise 8: Your Code Here

random_matrix = # Your code here

print(random_matrix)
print('Shape:', random_matrix.shape)


## Exercise 9: Slice a Sub-array 

### Problem:
From the given matrix, extract the **center 2×2** sub-array.

```python
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
```

**Expected Output:**
```
[[ 6  7]
 [10 11]]
```


In [ ]:
# Exercise 10: Your Code Here
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

center = # Your code here

print(center)


## Exercise 10: Broadcasting - Add a Row 

### Problem:
Add the array `[100, 200, 300]` to **each row** of the matrix below.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
```

**Expected Output:**
```
[[101 202 303]
 [104 205 306]
 [107 208 309]]
```


In [ ]:
# Exercise 11: Your Code Here
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

to_add = np.array([100, 200, 300])

result = # Your code here

print('Original:\n', matrix)
print('\nResult:\n', result)


## Exercise 11: Dot Product

### Problem:
Calculate the **dot product** of these two arrays:

```python
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
```

**Expected Output:**
```
70
```


In [ ]:
# Exercise 12: Your Code Here
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

dot_product = # Your code here

print('Dot product:', dot_product)


## Exercise 12: Normalize Data 

### Problem:
**Normalize** the array below:
- Formula: `(x - mean) / std_deviation`

```python
data = np.array([10, 20, 30, 40, 50])
```

**Expected Output (approximately):**
```
[-1.41 -0.71  0.    0.71  1.41]
```



In [ ]:
# Exercise 13: Your Code Here
data = np.array([10, 20, 30, 40, 50])




## Exercise 13: Final Challenge - Student Grade Analysis 

### Problem:
Analyze student performance across 3 subjects:

```python
# Rows = Students (5 students)
# Columns = Subjects (Math, English, Science)
grades = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 80],
                   [90, 92, 88],
                   [88, 86, 91]])
```

### Tasks:
1. Calculate the **average grade per student** (across all subjects)
2. Calculate the **average grade per subject** (across all students)
3. Find the **highest grade** overall
4. Find which **student** has the highest average
5. Count how many grades are **above 85**


In [ ]:
# Exercise 15: Your Code Here
grades = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [78, 85, 80],
                   [90, 92, 88],
                   [88, 86, 91]])




